services:
  postgres:
    image: postgres:16-alpine
    container_name: onyx-postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 2s
      timeout: 5s
      retries: 10

  auth_migration:
    build:
      context: .
      dockerfile: ./build/migrations/Dockerfile
    environment:
      SCHEMA: auth
    env_file: [.env]
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations/auth:/migrations

  users_migration:
    build:
      context: .
      dockerfile: ./build/migrations/Dockerfile
    environment:
      SCHEMA: users
    env_file: [.env]
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations/users:/migrations

  auth-service:
    build:
      context: .
      dockerfile: ./build/services/Dockerfile
      args:
        SERVICE: auth
    container_name: onyx-auth-service
    env_file:
      - .env
    environment:
      - LOGGER_PREFIX=auth-service
      - POSTGRES_SCHEMA=auth
    ports:
      - "${SERVICES_AUTH_GRPC_PORT}:${SERVICES_AUTH_GRPC_PORT}"
    healthcheck:
      test: ["CMD", "/grpc_health_probe", "-addr=:${SERVICES_AUTH_GRPC_PORT}"]
      interval: 2s
      timeout: 3s
      retries: 10
    depends_on:
      postgres:
        condition: service_healthy
      auth_migration:
        condition: service_completed_successfully

  user-service:
    build:
      context: .
      dockerfile: ./build/services/Dockerfile
      args:
        SERVICE: user
    container_name: onyx-user-service
    env_file:
      - .env
    environment:
      - LOGGER_PREFIX=user-service
      - POSTGRES_SCHEMA=users
    ports:
      - "${SERVICES_USER_GRPC_PORT}:${SERVICES_USER_GRPC_PORT}"
    healthcheck:
      test: ["CMD", "/grpc_health_probe", "-addr=:${SERVICES_USER_GRPC_PORT}"]
      interval: 2s
      timeout: 3s
      retries: 10
    depends_on:
      postgres:
        condition: service_healthy
      users_migration:
        condition: service_completed_successfully

  gateway:
    build:
      context: .
      dockerfile: ./build/gateway/Dockerfile
    container_name: onyx-gateway
    env_file:
      - .env
    ports:
      - "${GATEWAY_HTTP_PORT}:${GATEWAY_HTTP_PORT}"
    depends_on:
      auth-service:
        condition: service_healthy
      user-service:
        condition: service_healthy

volumes:
  pgdata:
