services:

  auth-service:
    container_name: onyx-${AUTH_SVC_NAME}
    build:
      context: .
      dockerfile: build/service/Dockerfile
      args:
        SERVICE_NAME: ${AUTH_SVC_NAME}
    ports:
      - "50151:${AUTH_SVC_GRPC_PORT}"
    env_file:
      - .env

  user-service:
    container_name: onyx-${USER_SVC_NAME}
    build:
      context: .
      dockerfile: build/service/Dockerfile
      args:
        SERVICE_NAME: ${USER_SVC_NAME}
    ports:
      - "50152:${USER_SVC_GRPC_PORT}"
    env_file:
      - .env

  gateway:
    container_name: onyx-${GATEWAY_NAME}
    build:
      context: .
      dockerfile: build/service/Dockerfile
      args:
        SERVICE_NAME: ${GATEWAY_NAME}
    ports:
      - "8080:${GATEWAY_HTTP_PORT}"
    env_file:
      - .env
    depends_on:
      - auth-service
      - user-service