services:

  auth-service:
    container_name: onyx-${AUTH_SVC_NAME}
    build:
      context: .
      dockerfile: build/service/Dockerfile
      args:
        SERVICE_NAME: ${AUTH_SVC_NAME}
    ports:
      - "${AUTH_SVC_GRPC_PORT}:${AUTH_SVC_GRPC_PORT}"
    env_file:
      - .env

  gateway:
    container_name: onyx-${GATEWAY_NAME}
    build:
      context: .
      dockerfile: build/service/Dockerfile
      args:
        SERVICE_NAME: ${GATEWAY_NAME}
    ports:
      - "${GATEWAY_HTTP_PORT}:${GATEWAY_HTTP_PORT}"
    env_file:
      - .env
    depends_on:
      - auth-service