#!/usr/bin/env bash
set -euo pipefail

OUT_DIR="./pkg/proto/gen"

rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

mapfile -t PROTO_FILES < <(find ./pkg/proto -name "*.proto" -not -path "./pkg/proto/gen/*")

protoc \
  --proto_path=./pkg/proto \
  --proto_path=/opt/googleapis \
  --go_out="$OUT_DIR" --go_opt=paths=source_relative \
  --go-grpc_out="$OUT_DIR" --go-grpc_opt=paths=source_relative \
  --grpc-gateway_out="$OUT_DIR" --grpc-gateway_opt=paths=source_relative \
  --openapiv3_out="$OUT_DIR" \
  "${PROTO_FILES[@]}"

# Generate one embed file per service (parent of vN dirs), with a versioned
# variable for each proto version found.
declare -A SERVICE_EMBEDS

while IFS= read -r spec_file; do
  version_dir=$(dirname "$spec_file")            # .../auth/v1
  service_dir=$(dirname "$version_dir")          # .../auth
  version=$(basename "$version_dir")             # v1
  service=$(basename "$service_dir")             # auth
  filename=$(basename "$spec_file")              # auth.openapi.json

  var_name="$(tr '[:lower:]' '[:upper:]' <<< "${service:0:1}")${service:1}$(tr '[:lower:]' '[:upper:]' <<< "${version:0:1}")${version:1}OpenAPISpec"
  embed_line="//go:embed ${version}/${filename}
var ${var_name} []byte
"
  SERVICE_EMBEDS["$service_dir"]+="$embed_line"
done < <(find "$OUT_DIR" -name "*.openapi.json")

for service_dir in "${!SERVICE_EMBEDS[@]}"; do
  package=$(basename "$service_dir")
  {
    echo "// Code generated by protobuild. DO NOT EDIT."
    echo "package ${package}"
    echo
    echo "import _ \"embed\""
    echo
    echo "${SERVICE_EMBEDS[$service_dir]}"
  } > "$service_dir/openapi.gen.go"
done

echo "Proto generation complete."